/**
 * Gonebusy01RubyNodePHPLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io )
 */

'use strict';

const BaseModel = require('./BaseModel');

/**
 * Creates an instance of CreatePricingModelBody
 */
class CreatePricingModelBody extends BaseModel {
    /**
     * @constructor
     * @param   {Object}  obj    The object passed to constructor
     */
    constructor(obj) {
        super(obj);
        if (obj === undefined || obj === null) return;
        this.name = this.constructor.getValue(obj.name);
        this.type = this.constructor.getValue(obj.type);
        this.currency = this.constructor.getValue(obj.currency);
        this.notes = this.constructor.getValue(obj.notes);
        this.price = this.constructor.getValue(obj.price);
        this.userId = this.constructor.getValue(obj.userId || obj.user_id);
    }

    /**
     * Function containing information about the fields of this model
     * @return   {array}   Array of objects containing information about the fields
     */
    static mappingInfo() {
        return super.mappingInfo().concat([
            { name: 'name', realName: 'name' },
            { name: 'type', realName: 'type' },
            { name: 'currency', realName: 'currency' },
            { name: 'notes', realName: 'notes' },
            { name: 'price', realName: 'price' },
            { name: 'userId', realName: 'user_id' },
        ]);
    }
}

module.exports = CreatePricingModelBody;
