/**
 * Gonebusy01RubyNodePHPLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io )
 */

'use strict';

const BaseModel = require('./BaseModel');

/**
 * Creates an instance of CreateBookingBody
 */
class CreateBookingBody extends BaseModel {
    /**
     * @constructor
     * @param   {Object}  obj    The object passed to constructor
     */
    constructor(obj) {
        super(obj);
        if (obj === undefined || obj === null) return;
        this.date = this.constructor.getValue(obj.date);
        this.serviceId = this.constructor.getValue(obj.serviceId || obj.service_id);
        this.time = this.constructor.getValue(obj.time);
        this.dateRecursBy = this.constructor.getValue(obj.dateRecursBy || obj.date_recurs_by);
        this.days = this.constructor.getValue(obj.days);
        this.duration = this.constructor.getValue(obj.duration);
        this.endDate = this.constructor.getValue(obj.endDate || obj.end_date);
        this.frequency = this.constructor.getValue(obj.frequency);
        this.occurrence = this.constructor.getValue(obj.occurrence);
        this.recursBy = this.constructor.getValue(obj.recursBy || obj.recurs_by);
        this.resourceId = this.constructor.getValue(obj.resourceId || obj.resource_id);
        this.userId = this.constructor.getValue(obj.userId || obj.user_id);
    }

    /**
     * Function containing information about the fields of this model
     * @return   {array}   Array of objects containing information about the fields
     */
    static mappingInfo() {
        return super.mappingInfo().concat([
            { name: 'date', realName: 'date', isDateTime: true },
            { name: 'serviceId', realName: 'service_id' },
            { name: 'time', realName: 'time' },
            { name: 'dateRecursBy', realName: 'date_recurs_by' },
            { name: 'days', realName: 'days' },
            { name: 'duration', realName: 'duration' },
            { name: 'endDate', realName: 'end_date', isDateTime: true },
            { name: 'frequency', realName: 'frequency' },
            { name: 'occurrence', realName: 'occurrence' },
            { name: 'recursBy', realName: 'recurs_by' },
            { name: 'resourceId', realName: 'resource_id' },
            { name: 'userId', realName: 'user_id' },
        ]);
    }
}

module.exports = CreateBookingBody;
