/**
 * Gonebusy01RubyNodePHPLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io )
 */

'use strict';

const BaseModel = require('./BaseModel');

/**
 * Creates an instance of CreateServiceBody
 */
class CreateServiceBody extends BaseModel {
    /**
     * @constructor
     * @param   {Object}  obj    The object passed to constructor
     */
    constructor(obj) {
        super(obj);
        if (obj === undefined || obj === null) return;
        this.description = this.constructor.getValue(obj.description);
        this.duration = this.constructor.getValue(obj.duration);
        this.name = this.constructor.getValue(obj.name);
        this.categories = this.constructor.getValue(obj.categories);
        this.maxDuration = this.constructor.getValue(obj.maxDuration || obj.max_duration);
        this.priceModelId = this.constructor.getValue(obj.priceModelId || obj.price_model_id);
        this.resources = this.constructor.getValue(obj.resources);
        this.shortName = this.constructor.getValue(obj.shortName || obj.short_name);
        this.userId = this.constructor.getValue(obj.userId || obj.user_id);
    }

    /**
     * Function containing information about the fields of this model
     * @return   {array}   Array of objects containing information about the fields
     */
    static mappingInfo() {
        return super.mappingInfo().concat([
            { name: 'description', realName: 'description' },
            { name: 'duration', realName: 'duration' },
            { name: 'name', realName: 'name' },
            { name: 'categories', realName: 'categories' },
            { name: 'maxDuration', realName: 'max_duration' },
            { name: 'priceModelId', realName: 'price_model_id' },
            { name: 'resources', realName: 'resources' },
            { name: 'shortName', realName: 'short_name' },
            { name: 'userId', realName: 'user_id' },
        ]);
    }
}

module.exports = CreateServiceBody;
