/**
 * gonebusy
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io )
 */

'use strict';

const BaseModel = require('./BaseModel');

/**
 * Creates an instance of CreateCategoryBody
 */
class CreateCategoryBody extends BaseModel {
    /**
     * @constructor
     * @param   {Object}  obj    The object passed to constructor
     */
    constructor(obj) {
        super(obj);
        if (obj === undefined || obj === null) return;
        this.name = this.constructor.getValue(obj.name);
        this.description = this.constructor.getValue(obj.description);
        this.shortName = this.constructor.getValue(obj.shortName || obj.short_name);
        this.longName = this.constructor.getValue(obj.longName || obj.long_name);
        this.parentCategoryId =
          this.constructor.getValue(obj.parentCategoryId
     || obj.parent_category_id);
    }

    /**
     * Function containing information about the fields of this model
     * @return   {array}   Array of objects containing information about the fields
     */
    static mappingInfo() {
        return super.mappingInfo().concat([
            { name: 'name', realName: 'name' },
            { name: 'description', realName: 'description' },
            { name: 'shortName', realName: 'short_name' },
            { name: 'longName', realName: 'long_name' },
            { name: 'parentCategoryId', realName: 'parent_category_id' },
        ]);
    }
}

module.exports = CreateCategoryBody;
