/**
 * Gonebusy01RubyNodePHPLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io )
 */

'use strict';

const BaseModel = require('./BaseModel');

/**
 * Creates an instance of CreateScheduleTimeWindowBody
 */
class CreateScheduleTimeWindowBody extends BaseModel {
    /**
     * @constructor
     * @param   {Object}  obj    The object passed to constructor
     */
    constructor(obj) {
        super(obj);
        if (obj === undefined || obj === null) return;
        this.days = this.constructor.getValue(obj.days);
        this.endTime = this.constructor.getValue(obj.endTime || obj.end_time);
        this.recursBy = this.constructor.getValue(obj.recursBy || obj.recurs_by);
        this.startDate = this.constructor.getValue(obj.startDate || obj.start_date);
        this.startTime = this.constructor.getValue(obj.startTime || obj.start_time);
        this.dateRecursBy = this.constructor.getValue(obj.dateRecursBy || obj.date_recurs_by);
        this.endDate = this.constructor.getValue(obj.endDate || obj.end_date);
        this.frequency = this.constructor.getValue(obj.frequency);
        this.occurrence = this.constructor.getValue(obj.occurrence);
        this.totalMinutes = this.constructor.getValue(obj.totalMinutes || obj.total_minutes);
    }

    /**
     * Function containing information about the fields of this model
     * @return   {array}   Array of objects containing information about the fields
     */
    static mappingInfo() {
        return super.mappingInfo().concat([
            { name: 'days', realName: 'days' },
            { name: 'endTime', realName: 'end_time' },
            { name: 'recursBy', realName: 'recurs_by' },
            { name: 'startDate', realName: 'start_date', isDateTime: true },
            { name: 'startTime', realName: 'start_time' },
            { name: 'dateRecursBy', realName: 'date_recurs_by' },
            { name: 'endDate', realName: 'end_date', isDateTime: true },
            { name: 'frequency', realName: 'frequency' },
            { name: 'occurrence', realName: 'occurrence' },
            { name: 'totalMinutes', realName: 'total_minutes' },
        ]);
    }
}

module.exports = CreateScheduleTimeWindowBody;
