/**
 * Gonebusy01RubyNodePHPLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io )
 */

'use strict';

const DateRecursByEnum = {

    // TODO: Write general description for this element
    DAY_IN_MONTH: 'day_in_month',

    // TODO: Write general description for this element
    DAY_IN_YEAR: 'day_in_year',

    // TODO: Write general description for this element
    DATE_IN_MONTH: 'date_in_month',

    // TODO: Write general description for this element
    DATE_IN_YEAR: 'date_in_year',

    // TODO: Write general description for this element
    DAY_IN_QUARTER: 'day_in_quarter',

    // TODO: Write general description for this element
    DATE_IN_QUARTER: 'date_in_quarter',

};

module.exports = DateRecursByEnum;
