/**
 * gonebusy
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io )
 */

'use strict';

const BaseModel = require('./BaseModel');

/**
 * Creates an instance of EntitiesBookingResponse
 */
class EntitiesBookingResponse extends BaseModel {
    /**
     * @constructor
     * @param   {Object}  obj    The object passed to constructor
     */
    constructor(obj) {
        super(obj);
        if (obj === undefined || obj === null) return;
        this.id = this.constructor.getValue(obj.id);
        this.ownerId = this.constructor.getValue(obj.ownerId || obj.owner_id);
        this.workflowState = this.constructor.getValue(obj.workflowState || obj.workflow_state);
        this.userMessage = this.constructor.getValue(obj.userMessage || obj.user_message);
        this.timeWindow = this.constructor.getValue(obj.timeWindow || obj.time_window);
    }

    /**
     * Function containing information about the fields of this model
     * @return   {array}   Array of objects containing information about the fields
     */
    static mappingInfo() {
        return super.mappingInfo().concat([
            { name: 'id', realName: 'id' },
            { name: 'ownerId', realName: 'owner_id' },
            { name: 'workflowState', realName: 'workflow_state' },
            { name: 'userMessage', realName: 'user_message' },
            { name: 'timeWindow', realName: 'time_window', type: 'EntitiesTimeWindowResponse' },
        ]);
    }
}

module.exports = EntitiesBookingResponse;
