/**
 * gonebusy
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io )
 */

'use strict';

const BaseModel = require('./BaseModel');

/**
 * Creates an instance of EntitiesBookingResponse
 */
class EntitiesBookingResponse extends BaseModel {
    /**
     * @constructor
     * @param   {Object}  obj    The object passed to constructor
     */
    constructor(obj) {
        super(obj);
        if (obj === undefined || obj === null) return;
        this.id = this.constructor.getValue(obj.id);
        this.ownerId = this.constructor.getValue(obj.ownerId || obj.owner_id);
        this.workflowState = this.constructor.getValue(obj.workflowState || obj.workflow_state);
        this.name = this.constructor.getValue(obj.name);
        this.timeWindow = this.constructor.getValue(obj.timeWindow || obj.time_window);
        this.resourceId = this.constructor.getValue(obj.resourceId || obj.resource_id);
        this.serviceId = this.constructor.getValue(obj.serviceId || obj.service_id);
        this.description = this.constructor.getValue(obj.description);
        this.externalUrl = this.constructor.getValue(obj.externalUrl || obj.external_url);
        this.collaborativeUrl =
          this.constructor.getValue(obj.collaborativeUrl
     || obj.collaborative_url);
    }

    /**
     * Function containing information about the fields of this model
     * @return   {array}   Array of objects containing information about the fields
     */
    static mappingInfo() {
        return super.mappingInfo().concat([
            { name: 'id', realName: 'id' },
            { name: 'ownerId', realName: 'owner_id' },
            { name: 'workflowState', realName: 'workflow_state' },
            { name: 'name', realName: 'name' },
            { name: 'timeWindow', realName: 'time_window', type: 'EntitiesTimeWindowResponse' },
            { name: 'resourceId', realName: 'resource_id' },
            { name: 'serviceId', realName: 'service_id' },
            { name: 'description', realName: 'description' },
            { name: 'externalUrl', realName: 'external_url' },
            { name: 'collaborativeUrl', realName: 'collaborative_url' },
        ]);
    }

    /**
     * Function containing information about discriminator values
     * mapped with their corresponding model class names
     *
     * @return   {object}  Object containing Key-Value pairs mapping discriminator
     *                     values with their corresponding model classes
     */
    static discriminatorMap() {
        return {};
    }
}

module.exports = EntitiesBookingResponse;
