/**
 * gonebusy
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io )
 */

'use strict';

const BaseModel = require('./BaseModel');

/**
 * Creates an instance of EntitiesResourceAvailabilities
 */
class EntitiesResourceAvailabilities extends BaseModel {
    /**
     * @constructor
     * @param   {Object}  obj    The object passed to constructor
     */
    constructor(obj) {
        super(obj);
        if (obj === undefined || obj === null) return;
        this.id = this.constructor.getValue(obj.id);
        this.availableSlots = this.constructor.getValue(obj.availableSlots || obj.available_slots);
    }

    /**
     * Function containing information about the fields of this model
     * @return   {array}   Array of objects containing information about the fields
     */
    static mappingInfo() {
        return super.mappingInfo().concat([
            { name: 'id', realName: 'id' },
            {
                name: 'availableSlots',
                realName: 'available_slots',
                array: true,
                type: 'EntitiesSlots',
            },
        ]);
    }
}

module.exports = EntitiesResourceAvailabilities;
