/**
 * gonebusy
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io )
 */

'use strict';

const BaseModel = require('./BaseModel');

/**
 * Creates an instance of EntitiesAddressEntity
 */
class EntitiesAddressEntity extends BaseModel {
    /**
     * @constructor
     * @param   {Object}  obj    The object passed to constructor
     */
    constructor(obj) {
        super(obj);
        if (obj === undefined || obj === null) return;
        this.line1 = this.constructor.getValue(obj.line1);
        this.line2 = this.constructor.getValue(obj.line2);
        this.city = this.constructor.getValue(obj.city);
        this.state = this.constructor.getValue(obj.state);
        this.province = this.constructor.getValue(obj.province);
        this.postalCode = this.constructor.getValue(obj.postalCode || obj.postal_code);
        this.country = this.constructor.getValue(obj.country);
        this.countryCode = this.constructor.getValue(obj.countryCode || obj.country_code);
        this.latitude = this.constructor.getValue(obj.latitude);
        this.longitude = this.constructor.getValue(obj.longitude);
    }

    /**
     * Function containing information about the fields of this model
     * @return   {array}   Array of objects containing information about the fields
     */
    static mappingInfo() {
        return super.mappingInfo().concat([
            { name: 'line1', realName: 'line1' },
            { name: 'line2', realName: 'line2' },
            { name: 'city', realName: 'city' },
            { name: 'state', realName: 'state' },
            { name: 'province', realName: 'province' },
            { name: 'postalCode', realName: 'postal_code' },
            { name: 'country', realName: 'country' },
            { name: 'countryCode', realName: 'country_code' },
            { name: 'latitude', realName: 'latitude' },
            { name: 'longitude', realName: 'longitude' },
        ]);
    }

    /**
     * Function containing information about discriminator values
     * mapped with their corresponding model class names
     *
     * @return   {object}  Object containing Key-Value pairs mapping discriminator
     *                     values with their corresponding model classes
     */
    static discriminatorMap() {
        return {};
    }
}

module.exports = EntitiesAddressEntity;
