/**
 * Gonebusy01RubyNodePHPLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io )
 */

'use strict';

const BaseModel = require('./BaseModel');

/**
 * Creates an instance of EntitiesPricingModelResponse
 */
class EntitiesPricingModelResponse extends BaseModel {
    /**
     * @constructor
     * @param   {Object}  obj    The object passed to constructor
     */
    constructor(obj) {
        super(obj);
        if (obj === undefined || obj === null) return;
        this.currency = this.constructor.getValue(obj.currency);
        this.id = this.constructor.getValue(obj.id);
        this.name = this.constructor.getValue(obj.name);
        this.notes = this.constructor.getValue(obj.notes);
        this.ownerId = this.constructor.getValue(obj.ownerId || obj.owner_id);
        this.price = this.constructor.getValue(obj.price);
        this.pricingModelType =
          this.constructor.getValue(obj.pricingModelType
     || obj.pricing_model_type);
    }

    /**
     * Function containing information about the fields of this model
     * @return   {array}   Array of objects containing information about the fields
     */
    static mappingInfo() {
        return super.mappingInfo().concat([
            { name: 'currency', realName: 'currency' },
            { name: 'id', realName: 'id' },
            { name: 'name', realName: 'name' },
            { name: 'notes', realName: 'notes' },
            { name: 'ownerId', realName: 'owner_id' },
            { name: 'price', realName: 'price' },
            { name: 'pricingModelType', realName: 'pricing_model_type' },
        ]);
    }
}

module.exports = EntitiesPricingModelResponse;
