/**
 * Gonebusy01RubyNodePHPLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io )
 */

'use strict';

const BaseModel = require('./BaseModel');

/**
 * Creates an instance of EntitiesSearchResponse
 */
class EntitiesSearchResponse extends BaseModel {
    /**
     * @constructor
     * @param   {Object}  obj    The object passed to constructor
     */
    constructor(obj) {
        super(obj);
        if (obj === undefined || obj === null) return;
        this.services = this.constructor.getValue(obj.services);
        this.users = this.constructor.getValue(obj.users);
    }

    /**
     * Function containing information about the fields of this model
     * @return   {array}   Array of objects containing information about the fields
     */
    static mappingInfo() {
        return super.mappingInfo().concat([
            {
                name: 'services',
                realName: 'services',
                array: true,
                type: 'EntitiesServiceResponse',
            },
            { name: 'users', realName: 'users', array: true, type: 'EntitiesUserResponse' },
        ]);
    }
}

module.exports = EntitiesSearchResponse;
