/**
 * gonebusy
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io )
 */

'use strict';

const BaseModel = require('./BaseModel');

/**
 * Creates an instance of EntitiesResourceResponse
 */
class EntitiesResourceResponse extends BaseModel {
    /**
     * @constructor
     * @param   {Object}  obj    The object passed to constructor
     */
    constructor(obj) {
        super(obj);
        if (obj === undefined || obj === null) return;
        this.id = this.constructor.getValue(obj.id);
        this.name = this.constructor.getValue(obj.name);
        this.description = this.constructor.getValue(obj.description);
        this.ownerId = this.constructor.getValue(obj.ownerId || obj.owner_id);
        this.resourceType = this.constructor.getValue(obj.resourceType || obj.resource_type);
        this.capacity = this.constructor.getValue(obj.capacity);
        this.gender = this.constructor.getValue(obj.gender);
        this.thingTypeId = this.constructor.getValue(obj.thingTypeId || obj.thing_type_id);
        this.primaryCal = this.constructor.getValue(obj.primaryCal || obj.primary_cal);
    }

    /**
     * Function containing information about the fields of this model
     * @return   {array}   Array of objects containing information about the fields
     */
    static mappingInfo() {
        return super.mappingInfo().concat([
            { name: 'id', realName: 'id' },
            { name: 'name', realName: 'name' },
            { name: 'description', realName: 'description' },
            { name: 'ownerId', realName: 'owner_id' },
            { name: 'resourceType', realName: 'resource_type' },
            { name: 'capacity', realName: 'capacity' },
            { name: 'gender', realName: 'gender' },
            { name: 'thingTypeId', realName: 'thing_type_id' },
            { name: 'primaryCal', realName: 'primary_cal' },
        ]);
    }
}

module.exports = EntitiesResourceResponse;
