/**
 * Gonebusy01RubyNodePHPLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io )
 */

'use strict';

const BaseModel = require('./BaseModel');

/**
 * Creates an instance of EntitiesUserResponse
 */
class EntitiesUserResponse extends BaseModel {
    /**
     * @constructor
     * @param   {Object}  obj    The object passed to constructor
     */
    constructor(obj) {
        super(obj);
        if (obj === undefined || obj === null) return;
        this.accountManagerId =
          this.constructor.getValue(obj.accountManagerId
     || obj.account_manager_id);
        this.address = this.constructor.getValue(obj.address);
        this.businessName = this.constructor.getValue(obj.businessName || obj.business_name);
        this.disabled = this.constructor.getValue(obj.disabled);
        this.email = this.constructor.getValue(obj.email);
        this.externalUrl = this.constructor.getValue(obj.externalUrl || obj.external_url);
        this.firstName = this.constructor.getValue(obj.firstName || obj.first_name);
        this.id = this.constructor.getValue(obj.id);
        this.lastName = this.constructor.getValue(obj.lastName || obj.last_name);
        this.permalink = this.constructor.getValue(obj.permalink);
        this.phone = this.constructor.getValue(obj.phone);
        this.resourceId = this.constructor.getValue(obj.resourceId || obj.resource_id);
        this.role = this.constructor.getValue(obj.role);
        this.timezone = this.constructor.getValue(obj.timezone);
    }

    /**
     * Function containing information about the fields of this model
     * @return   {array}   Array of objects containing information about the fields
     */
    static mappingInfo() {
        return super.mappingInfo().concat([
            { name: 'accountManagerId', realName: 'account_manager_id' },
            { name: 'address', realName: 'address', type: 'EntitiesAddressEntity' },
            { name: 'businessName', realName: 'business_name' },
            { name: 'disabled', realName: 'disabled' },
            { name: 'email', realName: 'email' },
            { name: 'externalUrl', realName: 'external_url' },
            { name: 'firstName', realName: 'first_name' },
            { name: 'id', realName: 'id' },
            { name: 'lastName', realName: 'last_name' },
            { name: 'permalink', realName: 'permalink' },
            { name: 'phone', realName: 'phone' },
            { name: 'resourceId', realName: 'resource_id' },
            { name: 'role', realName: 'role' },
            { name: 'timezone', realName: 'timezone' },
        ]);
    }
}

module.exports = EntitiesUserResponse;
