/**
 * gonebusy
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io )
 */

'use strict';

const BaseModel = require('./BaseModel');

/**
 * Creates an instance of EntitiesServiceResponse
 */
class EntitiesServiceResponse extends BaseModel {
    /**
     * @constructor
     * @param   {Object}  obj    The object passed to constructor
     */
    constructor(obj) {
        super(obj);
        if (obj === undefined || obj === null) return;
        this.id = this.constructor.getValue(obj.id);
        this.ownerId = this.constructor.getValue(obj.ownerId || obj.owner_id);
        this.name = this.constructor.getValue(obj.name);
        this.shortName = this.constructor.getValue(obj.shortName || obj.short_name);
        this.duration = this.constructor.getValue(obj.duration);
        this.maxDuration = this.constructor.getValue(obj.maxDuration || obj.max_duration);
        this.description = this.constructor.getValue(obj.description);
        this.priceModelId = this.constructor.getValue(obj.priceModelId || obj.price_model_id);
        this.isActive = this.constructor.getValue(obj.isActive || obj.is_active);
        this.categories = this.constructor.getValue(obj.categories);
        this.resources = this.constructor.getValue(obj.resources);
        this.schedules = this.constructor.getValue(obj.schedules);
    }

    /**
     * Function containing information about the fields of this model
     * @return   {array}   Array of objects containing information about the fields
     */
    static mappingInfo() {
        return super.mappingInfo().concat([
            { name: 'id', realName: 'id' },
            { name: 'ownerId', realName: 'owner_id' },
            { name: 'name', realName: 'name' },
            { name: 'shortName', realName: 'short_name' },
            { name: 'duration', realName: 'duration' },
            { name: 'maxDuration', realName: 'max_duration' },
            { name: 'description', realName: 'description' },
            { name: 'priceModelId', realName: 'price_model_id' },
            { name: 'isActive', realName: 'is_active' },
            { name: 'categories', realName: 'categories', array: true },
            { name: 'resources', realName: 'resources', array: true },
            { name: 'schedules', realName: 'schedules', array: true },
        ]);
    }

    /**
     * Function containing information about discriminator values
     * mapped with their corresponding model class names
     *
     * @return   {object}  Object containing Key-Value pairs mapping discriminator
     *                     values with their corresponding model classes
     */
    static discriminatorMap() {
        return {};
    }
}

module.exports = EntitiesServiceResponse;
