/**
 * Gonebusy01RubyNodePHPLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io )
 */

'use strict';

const BaseModel = require('./BaseModel');

/**
 * Creates an instance of EntitiesAvailabilityResponse
 */
class EntitiesAvailabilityResponse extends BaseModel {
    /**
     * @constructor
     * @param   {Object}  obj    The object passed to constructor
     */
    constructor(obj) {
        super(obj);
        if (obj === undefined || obj === null) return;
        this.id = this.constructor.getValue(obj.id);
        this.ownerId = this.constructor.getValue(obj.ownerId || obj.owner_id);
        this.resources = this.constructor.getValue(obj.resources);
    }

    /**
     * Function containing information about the fields of this model
     * @return   {array}   Array of objects containing information about the fields
     */
    static mappingInfo() {
        return super.mappingInfo().concat([
            { name: 'id', realName: 'id' },
            { name: 'ownerId', realName: 'owner_id' },
            {
                name: 'resources',
                realName: 'resources',
                array: true,
                type: 'EntitiesResourceAvailabilities',
            },
        ]);
    }
}

module.exports = EntitiesAvailabilityResponse;
