/**
 * Gonebusy01RubyNodePHPLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io )
 */

'use strict';

const GenderEnum = {

    // TODO: Write general description for this element
    F: 'F',

    // TODO: Write general description for this element
    M: 'M',

    // TODO: Write general description for this element
    ENUM_TG: 'Enum_TG',

};

module.exports = GenderEnum;
