/**
 * gonebusy
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io )
 */

'use strict';

const BaseModel = require('./BaseModel');

/**
 * Creates an instance of GetPricingModelsResponse
 */
class GetPricingModelsResponse extends BaseModel {
    /**
     * @constructor
     * @param   {Object}  obj    The object passed to constructor
     */
    constructor(obj) {
        super(obj);
        if (obj === undefined || obj === null) return;
        this.pricingModels = this.constructor.getValue(obj.pricingModels || obj.pricing_models);
    }

    /**
     * Function containing information about the fields of this model
     * @return   {array}   Array of objects containing information about the fields
     */
    static mappingInfo() {
        return super.mappingInfo().concat([
            {
                name: 'pricingModels',
                realName: 'pricing_models',
                array: true,
                type: 'EntitiesPricingModelResponse',
            },
        ]);
    }
}

module.exports = GetPricingModelsResponse;
