/**
 * gonebusy
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io )
 */

'use strict';

const OccurrenceEnum = {

    /**
     * TODO: Write general description for this element
     */
    ENUM_4_TH_TO_LAST: '4th_to_last',

    /**
     * TODO: Write general description for this element
     */
    ENUM_3_RD_TO_LAST: '3rd_to_last',

    /**
     * TODO: Write general description for this element
     */
    ENUM_2_ND_TO_LAST: '2nd_to_last',

    /**
     * TODO: Write general description for this element
     */
    LAST: 'last',

    /**
     * TODO: Write general description for this element
     */
    EVERY: 'every',

    /**
     * TODO: Write general description for this element
     */
    FIRST: 'first',

    /**
     * TODO: Write general description for this element
     */
    ENUM_2_ND: '2nd',

    /**
     * TODO: Write general description for this element
     */
    ENUM_3_RD: '3rd',

    /**
     * TODO: Write general description for this element
     */
    ENUM_4_TH: '4th',

    /**
     * TODO: Write general description for this element
     */
    ENUM_5_TH: '5th',

    /**
     * TODO: Write general description for this element
     */
    ENUM_6_TH: '6th',

    /**
     * TODO: Write general description for this element
     */
    ENUM_7_TH: '7th',

    /**
     * TODO: Write general description for this element
     */
    ENUM_8_TH: '8th',

    /**
     * TODO: Write general description for this element
     */
    ENUM_9_TH: '9th',

    /**
     * TODO: Write general description for this element
     */
    ENUM_10_TH: '10th',

    /**
     * TODO: Write general description for this element
     */
    ENUM_11_TH: '11th',

    /**
     * TODO: Write general description for this element
     */
    ENUM_12_TH: '12th',

    /**
     * TODO: Write general description for this element
     */
    ENUM_13_TH: '13th',

    /**
     * TODO: Write general description for this element
     */
    ENUM_14_TH: '14th',

    /**
     * TODO: Write general description for this element
     */
    ENUM_15_TH: '15th',

    /**
     * TODO: Write general description for this element
     */
    ENUM_16_TH: '16th',

    /**
     * TODO: Write general description for this element
     */
    ENUM_17_TH: '17th',

    /**
     * TODO: Write general description for this element
     */
    ENUM_18_TH: '18th',

    /**
     * TODO: Write general description for this element
     */
    ENUM_19_TH: '19th',

    /**
     * TODO: Write general description for this element
     */
    ENUM_20_TH: '20th',

    /**
     * TODO: Write general description for this element
     */
    ENUM_21_ST: '21st',

    /**
     * TODO: Write general description for this element
     */
    ENUM_22_ND: '22nd',

    /**
     * TODO: Write general description for this element
     */
    ENUM_23_RD: '23rd',

    /**
     * TODO: Write general description for this element
     */
    ENUM_24_TH: '24th',

    /**
     * TODO: Write general description for this element
     */
    ENUM_25_TH: '25th',

    /**
     * TODO: Write general description for this element
     */
    ENUM_26_TH: '26th',

    /**
     * TODO: Write general description for this element
     */
    ENUM_27_TH: '27th',

    /**
     * TODO: Write general description for this element
     */
    ENUM_28_TH: '28th',

    /**
     * TODO: Write general description for this element
     */
    ENUM_29_TH: '29th',

    /**
     * TODO: Write general description for this element
     */
    ENUM_30_TH: '30th',

    /**
     * TODO: Write general description for this element
     */
    ENUM_31_ST: '31st',

    /**
     * TODO: Write general description for this element
     */
    ENUM_32_ND: '32nd',

    /**
     * TODO: Write general description for this element
     */
    ENUM_33_RD: '33rd',

    /**
     * TODO: Write general description for this element
     */
    ENUM_34_TH: '34th',

    /**
     * TODO: Write general description for this element
     */
    ENUM_35_TH: '35th',

    /**
     * TODO: Write general description for this element
     */
    ENUM_36_TH: '36th',

    /**
     * TODO: Write general description for this element
     */
    ENUM_37_TH: '37th',

    /**
     * TODO: Write general description for this element
     */
    ENUM_38_TH: '38th',

    /**
     * TODO: Write general description for this element
     */
    ENUM_39_TH: '39th',

    /**
     * TODO: Write general description for this element
     */
    ENUM_40_TH: '40th',

    /**
     * TODO: Write general description for this element
     */
    ENUM_41_ST: '41st',

    /**
     * TODO: Write general description for this element
     */
    ENUM_42_ND: '42nd',

    /**
     * TODO: Write general description for this element
     */
    ENUM_43_RD: '43rd',

    /**
     * TODO: Write general description for this element
     */
    ENUM_44_TH: '44th',

    /**
     * TODO: Write general description for this element
     */
    ENUM_45_TH: '45th',

    /**
     * TODO: Write general description for this element
     */
    ENUM_46_TH: '46th',

    /**
     * TODO: Write general description for this element
     */
    ENUM_47_TH: '47th',

    /**
     * TODO: Write general description for this element
     */
    ENUM_48_TH: '48th',

    /**
     * TODO: Write general description for this element
     */
    ENUM_49_TH: '49th',

    /**
     * TODO: Write general description for this element
     */
    ENUM_50_TH: '50th',

    /**
     * TODO: Write general description for this element
     */
    ENUM_51_ST: '51st',

    /**
     * TODO: Write general description for this element
     */
    ENUM_52_ND: '52nd',

};

module.exports = OccurrenceEnum;
