/**
 * gonebusy
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io )
 */

'use strict';

const OccurrenceEnum = {

    // TODO: Write general description for this element
    ENUM_4_TH_TO_LAST: 'Enum_4th_to_last',

    // TODO: Write general description for this element
    ENUM_3_RD_TO_LAST: 'Enum_3rd_to_last',

    // TODO: Write general description for this element
    ENUM_2_ND_TO_LAST: 'Enum_2nd_to_last',

    // TODO: Write general description for this element
    LAST: 'last',

    // TODO: Write general description for this element
    EVERY: 'every',

    // TODO: Write general description for this element
    FIRST: 'first',

    // TODO: Write general description for this element
    ENUM_2_ND: 'Enum_2nd',

    // TODO: Write general description for this element
    ENUM_3_RD: 'Enum_3rd',

    // TODO: Write general description for this element
    ENUM_4_TH: 'Enum_4th',

    // TODO: Write general description for this element
    ENUM_5_TH: 'Enum_5th',

    // TODO: Write general description for this element
    ENUM_6_TH: 'Enum_6th',

    // TODO: Write general description for this element
    ENUM_7_TH: 'Enum_7th',

    // TODO: Write general description for this element
    ENUM_8_TH: 'Enum_8th',

    // TODO: Write general description for this element
    ENUM_9_TH: 'Enum_9th',

    // TODO: Write general description for this element
    ENUM_10_TH: 'Enum_10th',

};

module.exports = OccurrenceEnum;
