/**
 * gonebusy
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io )
 */

'use strict';

const RecursByEnum = {

    // TODO: Write general description for this element
    ONCE: 'once',

    // TODO: Write general description for this element
    DAILY: 'daily',

    // TODO: Write general description for this element
    WEEKEND: 'weekend',

    // TODO: Write general description for this element
    MON_WED_FRI: 'mon_wed_fri',

    // TODO: Write general description for this element
    TUE_THU: 'tue_thu',

    // TODO: Write general description for this element
    WEEKDAY: 'weekday',

    // TODO: Write general description for this element
    WEEKLY: 'weekly',

    // TODO: Write general description for this element
    MONTHLY: 'monthly',

    // TODO: Write general description for this element
    YEARLY: 'yearly',

};

module.exports = RecursByEnum;
