/**
 * gonebusy
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io )
 */

'use strict';

const BaseModel = require('./BaseModel');

/**
 * Creates an instance of UpdateBookingByIdBody
 */
class UpdateBookingByIdBody extends BaseModel {
    /**
     * @constructor
     * @param   {Object}  obj    The object passed to constructor
     */
    constructor(obj) {
        super(obj);
        if (obj === undefined || obj === null) return;
        this.date = this.constructor.getValue(obj.date);
        this.time = this.constructor.getValue(obj.time);
        this.duration = this.constructor.getValue(obj.duration);
        this.endDate = this.constructor.getValue(obj.endDate || obj.end_date);
        this.recursBy = this.constructor.getValue(obj.recursBy || obj.recurs_by);
        this.frequency = this.constructor.getValue(obj.frequency);
        this.days = this.constructor.getValue(obj.days);
        this.occurrence = this.constructor.getValue(obj.occurrence);
        this.dateRecursBy = this.constructor.getValue(obj.dateRecursBy || obj.date_recurs_by);
        this.updateRecurring =
          this.constructor.getValue(obj.updateRecurring
     || obj.update_recurring);
        this.name = this.constructor.getValue(obj.name);
        this.description = this.constructor.getValue(obj.description);
    }

    /**
     * Function containing information about the fields of this model
     * @return   {array}   Array of objects containing information about the fields
     */
    static mappingInfo() {
        return super.mappingInfo().concat([
            { name: 'date', realName: 'date', isDateTime: true },
            { name: 'time', realName: 'time' },
            { name: 'duration', realName: 'duration' },
            { name: 'endDate', realName: 'end_date', isDateTime: true },
            { name: 'recursBy', realName: 'recurs_by' },
            { name: 'frequency', realName: 'frequency' },
            { name: 'days', realName: 'days' },
            { name: 'occurrence', realName: 'occurrence' },
            { name: 'dateRecursBy', realName: 'date_recurs_by' },
            { name: 'updateRecurring', realName: 'update_recurring' },
            { name: 'name', realName: 'name' },
            { name: 'description', realName: 'description' },
        ]);
    }
}

module.exports = UpdateBookingByIdBody;
