/**
 * Gonebusy01RubyNodePHPLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io )
 */

'use strict';

const BaseModel = require('./BaseModel');

/**
 * Creates an instance of UpdateResourceByIdBody
 */
class UpdateResourceByIdBody extends BaseModel {
    /**
     * @constructor
     * @param   {Object}  obj    The object passed to constructor
     */
    constructor(obj) {
        super(obj);
        if (obj === undefined || obj === null) return;
        this.capacity = this.constructor.getValue(obj.capacity);
        this.description = this.constructor.getValue(obj.description);
        this.gender = this.constructor.getValue(obj.gender);
        this.name = this.constructor.getValue(obj.name);
        this.thingTypeId = this.constructor.getValue(obj.thingTypeId || obj.thing_type_id);
    }

    /**
     * Function containing information about the fields of this model
     * @return   {array}   Array of objects containing information about the fields
     */
    static mappingInfo() {
        return super.mappingInfo().concat([
            { name: 'capacity', realName: 'capacity' },
            { name: 'description', realName: 'description' },
            { name: 'gender', realName: 'gender' },
            { name: 'name', realName: 'name' },
            { name: 'thingTypeId', realName: 'thing_type_id' },
        ]);
    }
}

module.exports = UpdateResourceByIdBody;
