/**
 * gonebusy
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io )
 */

'use strict';

const BaseModel = require('./BaseModel');

/**
 * Creates an instance of UpdateUserByIdBody
 */
class UpdateUserByIdBody extends BaseModel {
    /**
     * @constructor
     * @param   {Object}  obj    The object passed to constructor
     */
    constructor(obj) {
        super(obj);
        if (obj === undefined || obj === null) return;
        this.email = this.constructor.getValue(obj.email);
        this.firstName = this.constructor.getValue(obj.firstName || obj.first_name);
        this.lastName = this.constructor.getValue(obj.lastName || obj.last_name);
        this.businessName = this.constructor.getValue(obj.businessName || obj.business_name);
        this.externalUrl = this.constructor.getValue(obj.externalUrl || obj.external_url);
        this.permalink = this.constructor.getValue(obj.permalink);
        this.timezone = this.constructor.getValue(obj.timezone);
    }

    /**
     * Function containing information about the fields of this model
     * @return   {array}   Array of objects containing information about the fields
     */
    static mappingInfo() {
        return super.mappingInfo().concat([
            { name: 'email', realName: 'email' },
            { name: 'firstName', realName: 'first_name' },
            { name: 'lastName', realName: 'last_name' },
            { name: 'businessName', realName: 'business_name' },
            { name: 'externalUrl', realName: 'external_url' },
            { name: 'permalink', realName: 'permalink' },
            { name: 'timezone', realName: 'timezone' },
        ]);
    }
}

module.exports = UpdateUserByIdBody;
