/**
 * Gonebusy01RubyNodePHPLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io )
 */

'use strict';

const Environments = {

    // TODO: Write general description for this element
    PRODUCTION: 'production',

    // https://sandbox.gonebusy.com/api/v1
    SANDBOX: 'sandbox',

};

module.exports = Environments;
