/**
 * gonebusy
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io )
 */

'use strict';

const Environments = {

    // https://www.gonebusy.com/api/v1
    PRODUCTION: 'production',

    // https://sandbox.gonebusy.com/api/v1
    SANDBOX: 'sandbox',

};

module.exports = Environments;
