/**
 * Gonebusy01RubyNodePHPLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io )
 */

'use strict';

const EntitiesAddressEntity = require('../lib/Models/EntitiesAddressEntity');
const EntitiesAvailabilityResponse = require('../lib/Models/EntitiesAvailabilityResponse');
const EntitiesResourceAvailabilities = require('../lib/Models/EntitiesResourceAvailabilities');
const EntitiesSlots = require('../lib/Models/EntitiesSlots');
const EntitiesBookingResponse = require('../lib/Models/EntitiesBookingResponse');
const EntitiesTimeWindowResponse = require('../lib/Models/EntitiesTimeWindowResponse');
const EntitiesCategoryResponse = require('../lib/Models/EntitiesCategoryResponse');
const EntitiesPricingModelResponse = require('../lib/Models/EntitiesPricingModelResponse');
const EntitiesResourceResponse = require('../lib/Models/EntitiesResourceResponse');
const EntitiesScheduleResponse = require('../lib/Models/EntitiesScheduleResponse');
const EntitiesSearchResponse = require('../lib/Models/EntitiesSearchResponse');
const EntitiesUserResponse = require('../lib/Models/EntitiesUserResponse');
const EntitiesServiceResponse = require('../lib/Models/EntitiesServiceResponse');
const EntitiesThingTypeResponse = require('../lib/Models/EntitiesThingTypeResponse');
const GetBookingsResponse = require('../lib/Models/GetBookingsResponse');
const CreateBookingBody = require('../lib/Models/CreateBookingBody');
const CreateBookingResponse = require('../lib/Models/CreateBookingResponse');
const GetBookingByIdResponse = require('../lib/Models/GetBookingByIdResponse');
const UpdateBookingByIdBody = require('../lib/Models/UpdateBookingByIdBody');
const UpdateBookingByIdResponse = require('../lib/Models/UpdateBookingByIdResponse');
const CancelBookingByIdResponse = require('../lib/Models/CancelBookingByIdResponse');
const GetCategoriesResponse = require('../lib/Models/GetCategoriesResponse');
const CreateCategoryBody = require('../lib/Models/CreateCategoryBody');
const CreateCategoryResponse = require('../lib/Models/CreateCategoryResponse');
const GetCategoryByIdResponse = require('../lib/Models/GetCategoryByIdResponse');
const GetPricingModelsResponse = require('../lib/Models/GetPricingModelsResponse');
const CreatePricingModelBody = require('../lib/Models/CreatePricingModelBody');
const CreatePricingModelResponse = require('../lib/Models/CreatePricingModelResponse');
const GetPricingModelByIdResponse = require('../lib/Models/GetPricingModelByIdResponse');
const UpdatePricingModelByIdBody = require('../lib/Models/UpdatePricingModelByIdBody');
const UpdatePricingModelByIdResponse = require('../lib/Models/UpdatePricingModelByIdResponse');
const GetResourcesResponse = require('../lib/Models/GetResourcesResponse');
const CreateResourceBody = require('../lib/Models/CreateResourceBody');
const CreateResourceResponse = require('../lib/Models/CreateResourceResponse');
const GetResourceThingsResponse = require('../lib/Models/GetResourceThingsResponse');
const GetResourceByIdResponse = require('../lib/Models/GetResourceByIdResponse');
const UpdateResourceByIdBody = require('../lib/Models/UpdateResourceByIdBody');
const UpdateResourceByIdResponse = require('../lib/Models/UpdateResourceByIdResponse');
const DeleteResourceByIdResponse = require('../lib/Models/DeleteResourceByIdResponse');
const GetSchedulesResponse = require('../lib/Models/GetSchedulesResponse');
const CreateScheduleBody = require('../lib/Models/CreateScheduleBody');
const CreateScheduleResponse = require('../lib/Models/CreateScheduleResponse');
const GetScheduleByIdResponse = require('../lib/Models/GetScheduleByIdResponse');
const DeleteScheduleByIdResponse = require('../lib/Models/DeleteScheduleByIdResponse');
const CreateScheduleTimeWindowBody = require('../lib/Models/CreateScheduleTimeWindowBody');
const CreateScheduleTimeWindowResponse = require('../lib/Models/CreateScheduleTimeWindowResponse');
const UpdateScheduleTimeWindowByIdBody = require('../lib/Models/UpdateScheduleTimeWindowByIdBody');
const UpdateScheduleTimeWindowByIdResponse =
  require('../lib/Models/UpdateScheduleTimeWindowByIdResponse');
const DeleteScheduleTimeWindowByIdResponse =
  require('../lib/Models/DeleteScheduleTimeWindowByIdResponse');
const SearchQueryResponse = require('../lib/Models/SearchQueryResponse');
const GetServicesResponse = require('../lib/Models/GetServicesResponse');
const CreateServiceBody = require('../lib/Models/CreateServiceBody');
const CreateServiceResponse = require('../lib/Models/CreateServiceResponse');
const GetServiceAvailableSlotsByIdResponse =
  require('../lib/Models/GetServiceAvailableSlotsByIdResponse');
const GetServiceByIdResponse = require('../lib/Models/GetServiceByIdResponse');
const UpdateServiceByIdBody = require('../lib/Models/UpdateServiceByIdBody');
const UpdateServiceByIdResponse = require('../lib/Models/UpdateServiceByIdResponse');
const DeleteServiceByIdResponse = require('../lib/Models/DeleteServiceByIdResponse');
const GetUsersResponse = require('../lib/Models/GetUsersResponse');
const CreateUserBody = require('../lib/Models/CreateUserBody');
const CreateUserResponse = require('../lib/Models/CreateUserResponse');
const GetUserByIdResponse = require('../lib/Models/GetUserByIdResponse');
const UpdateUserByIdBody = require('../lib/Models/UpdateUserByIdBody');
const UpdateUserByIdResponse = require('../lib/Models/UpdateUserByIdResponse');
const EntitiesErrorErrorException = require('../lib/Exceptions/EntitiesErrorErrorException');

const classMap = {
    EntitiesAddressEntity,
    EntitiesAvailabilityResponse,
    EntitiesResourceAvailabilities,
    EntitiesSlots,
    EntitiesBookingResponse,
    EntitiesTimeWindowResponse,
    EntitiesCategoryResponse,
    EntitiesPricingModelResponse,
    EntitiesResourceResponse,
    EntitiesScheduleResponse,
    EntitiesSearchResponse,
    EntitiesUserResponse,
    EntitiesServiceResponse,
    EntitiesThingTypeResponse,
    GetBookingsResponse,
    CreateBookingBody,
    CreateBookingResponse,
    GetBookingByIdResponse,
    UpdateBookingByIdBody,
    UpdateBookingByIdResponse,
    CancelBookingByIdResponse,
    GetCategoriesResponse,
    CreateCategoryBody,
    CreateCategoryResponse,
    GetCategoryByIdResponse,
    GetPricingModelsResponse,
    CreatePricingModelBody,
    CreatePricingModelResponse,
    GetPricingModelByIdResponse,
    UpdatePricingModelByIdBody,
    UpdatePricingModelByIdResponse,
    GetResourcesResponse,
    CreateResourceBody,
    CreateResourceResponse,
    GetResourceThingsResponse,
    GetResourceByIdResponse,
    UpdateResourceByIdBody,
    UpdateResourceByIdResponse,
    DeleteResourceByIdResponse,
    GetSchedulesResponse,
    CreateScheduleBody,
    CreateScheduleResponse,
    GetScheduleByIdResponse,
    DeleteScheduleByIdResponse,
    CreateScheduleTimeWindowBody,
    CreateScheduleTimeWindowResponse,
    UpdateScheduleTimeWindowByIdBody,
    UpdateScheduleTimeWindowByIdResponse,
    DeleteScheduleTimeWindowByIdResponse,
    SearchQueryResponse,
    GetServicesResponse,
    CreateServiceBody,
    CreateServiceResponse,
    GetServiceAvailableSlotsByIdResponse,
    GetServiceByIdResponse,
    UpdateServiceByIdBody,
    UpdateServiceByIdResponse,
    DeleteServiceByIdResponse,
    GetUsersResponse,
    CreateUserBody,
    CreateUserResponse,
    GetUserByIdResponse,
    UpdateUserByIdBody,
    UpdateUserByIdResponse,
    EntitiesErrorErrorException,
};

/**
 * Factory class to create instances of models and exception classes
 */
class ModelFactory {
    /**
     * Creates instance of a model class
     * @param  modelName  {string}  Name of class to instantiate
     * @returns  {object} Instance of the model class
     */
    static getInstance(modelName) {
        return new classMap[modelName]();
    }
}

module.exports = ModelFactory;
